### ISSUE TITLE
Getting error No module named 'core.models.seq2seq'

### ISSUE THREAD

**Issue by ganeshlandge** [sion-zcfei/IGND#2]
Tried to run the code using following commands:

> cd IGND/src
> python3 main.py

Getting following error:
> ModuleNotFoundError: No module named 'core.models.seq2seq'

The file '/src/core/models/seq2seq.py' seems to be missing.
Please fix this error!

**Comment by sion-zcfei** [comment]
> Tried to run the code using following commands:
> 
> > cd IGND/src
> > python3 main.py
> 
> Getting following error:
> 
> > ModuleNotFoundError: No module named 'core.models.seq2seq'
> 
> The file '/src/core/models/seq2seq.py' seems to be missing. Please fix this error!

This module is used to run some baseline, it is not relevant to IGND, please remove this import.
