### ISSUE TITLE
Missing data files

### ISSUE THREAD

**Issue by ganeshlandge** [sion-zcfei/IGND#3]
Following data files are absent in the repository:
> trainset: '../data/squad-split2/train_sent_pre.v5.json'
> devset: '../data/squad-split2/dev_sent_pre.v5.json'
> testset: '../data/squad-split2/test_sent_pre.v5.json'

Where can we get these files?

**Comment by ganeshlandge** [comment]
@sion-zcfei please let us know.

**Comment by sion-zcfei** [comment]
> @sion-zcfei please let us know.

I think I have given the url of this dataset in my paper.

**Comment by ganeshlandge** [comment]
> > @sion-zcfei please let us know.
> 
> I think I have given the url of this dataset in my paper.

I got the url provided in the paper, provided url is [https://res.qyzhou.me/redistribute.zip](https://res.qyzhou.me/redistribute.zip)
I have downloaded the dataset, but it seem to have different files.  The code is expecting 3 json files namely 'train_sent_pre.v5.json' , 'dev_sent_pre.v5.json' and 'test_sent_pre.v5.json'. But in the downloaded datset these files seems to be missing.

**Do I have to run some scripts to preprocess these data files to convert them into required format?**

Provided the tree view of downloaded dataset.
> redistribute
├── QG
│   ├── dev
│   │   ├── dev.txt.shuffle.dev.bio
│   │   ├── dev.txt.shuffle.dev.case
│   │   ├── dev.txt.shuffle.dev.ner
│   │   ├── dev.txt.shuffle.dev.pos
│   │   ├── dev.txt.shuffle.dev.source.txt
│   │   └── dev.txt.shuffle.dev.target.txt
│   ├── test
│   │   ├── dev.txt.shuffle.test.bio
│   │   ├── dev.txt.shuffle.test.case
│   │   ├── dev.txt.shuffle.test.ner
│   │   ├── dev.txt.shuffle.test.pos
│   │   ├── dev.txt.shuffle.test.source.txt
│   │   └── dev.txt.shuffle.test.target.txt
│   ├── test_sample
│   │   ├── dev.txt.shuffle.test.bio
│   │   ├── dev.txt.shuffle.test.case
│   │   ├── dev.txt.shuffle.test.ner
│   │   ├── dev.txt.shuffle.test.pos
│   │   ├── dev.txt.shuffle.test.source.txt
│   │   └── dev.txt.shuffle.test.target.txt
│   └── train
│       ├── train.txt.bio
│       ├── train.txt.case
│       ├── train.txt.ner
│       ├── train.txt.pos
│       ├── train.txt.source.txt
│       └── train.txt.target.txt
├── raw
│   ├── dev.txt.shuffle.dev
│   ├── dev.txt.shuffle.test
│   └── train.txt
└── Readme.txt

Thanks!!

**Comment by sion-zcfei** [comment]
> > > @sion-zcfei please let us know.
> > 
> > 
> > I think I have given the url of this dataset in my paper.
> 
> I got the url provided in the paper, provided url is https://res.qyzhou.me/redistribute.zip I have downloaded the dataset, but it seem to have different files. The code is expecting 3 json files namely 'train_sent_pre.v5.json' , 'dev_sent_pre.v5.json' and 'test_sent_pre.v5.json'. But in the downloaded datset these files seems to be missing.
> 
> **Do I have to run some scripts to preprocess these data files to convert them into required format?**
> 
> Provided the tree view of downloaded dataset.
> 
> > redistribute
> > ├── QG
> > │   ├── dev
> > │   │   ├── dev.txt.shuffle.dev.bio
> > │   │   ├── dev.txt.shuffle.dev.case
> > │   │   ├── dev.txt.shuffle.dev.ner
> > │   │   ├── dev.txt.shuffle.dev.pos
> > │   │   ├── dev.txt.shuffle.dev.source.txt
> > │   │   └── dev.txt.shuffle.dev.target.txt
> > │   ├── test
> > │   │   ├── dev.txt.shuffle.test.bio
> > │   │   ├── dev.txt.shuffle.test.case
> > │   │   ├── dev.txt.shuffle.test.ner
> > │   │   ├── dev.txt.shuffle.test.pos
> > │   │   ├── dev.txt.shuffle.test.source.txt
> > │   │   └── dev.txt.shuffle.test.target.txt
> > │   ├── test_sample
> > │   │   ├── dev.txt.shuffle.test.bio
> > │   │   ├── dev.txt.shuffle.test.case
> > │   │   ├── dev.txt.shuffle.test.ner
> > │   │   ├── dev.txt.shuffle.test.pos
> > │   │   ├── dev.txt.shuffle.test.source.txt
> > │   │   └── dev.txt.shuffle.test.target.txt
> > │   └── train
> > │       ├── train.txt.bio
> > │       ├── train.txt.case
> > │       ├── train.txt.ner
> > │       ├── train.txt.pos
> > │       ├── train.txt.source.txt
> > │       └── train.txt.target.txt
> > ├── raw
> > │   ├── dev.txt.shuffle.dev
> > │   ├── dev.txt.shuffle.test
> > │   └── train.txt
> > └── Readme.txt
> 
> Thanks!!

Sorry，this paper is so long ago. Try this url https://onedrive.live.com/?authkey=%21AJOw8oWPiHLhHNQ&id=3DDD4E15ECA69238%21200&cid=3DDD4E15ECA69238

**Comment by ganeshlandge** [comment]
> Sorry，this paper is so long ago. Try this url https://onedrive.live.com/?authkey=%21AJOw8oWPiHLhHNQ&id=3DDD4E15ECA69238%21200&cid=3DDD4E15ECA69238

Thanks for the quick response!!

**Comment by 2023aa05142** [comment]
@ganeshlandge were you able to download data files? I am unable to access above link - https://onedrive.live.com/?authkey=%21AJOw8oWPiHLhHNQ&id=3DDD4E15ECA69238%21200&cid=3DDD4E15ECA69238

**Comment by 2023aa05142** [comment]
@sion-zcfei Have you removed data files from above location 

> > > > [@sion-zcfei](https://github.com/sion-zcfei) please let us know.
> > > 
> > > 
> > > I think I have given the url of this dataset in my paper.
> > 
> > 
> > I got the url provided in the paper, provided url is https://res.qyzhou.me/redistribute.zip I have downloaded the dataset, but it seem to have different files. The code is expecting 3 json files namely 'train_sent_pre.v5.json' , 'dev_sent_pre.v5.json' and 'test_sent_pre.v5.json'. But in the downloaded datset these files seems to be missing.
> > **Do I have to run some scripts to preprocess these data files to convert them into required format?**
> > Provided the tree view of downloaded dataset.
> > > redistribute
> > > ├── QG
> > > │   ├── dev
> > > │   │   ├── dev.txt.shuffle.dev.bio
> > > │   │   ├── dev.txt.shuffle.dev.case
> > > │   │   ├── dev.txt.shuffle.dev.ner
> > > │   │   ├── dev.txt.shuffle.dev.pos
> > > │   │   ├── dev.txt.shuffle.dev.source.txt
> > > │   │   └── dev.txt.shuffle.dev.target.txt
> > > │   ├── test
> > > │   │   ├── dev.txt.shuffle.test.bio
> > > │   │   ├── dev.txt.shuffle.test.case
> > > │   │   ├── dev.txt.shuffle.test.ner
> > > │   │   ├── dev.txt.shuffle.test.pos
> > > │   │   ├── dev.txt.shuffle.test.source.txt
> > > │   │   └── dev.txt.shuffle.test.target.txt
> > > │   ├── test_sample
> > > │   │   ├── dev.txt.shuffle.test.bio
> > > │   │   ├── dev.txt.shuffle.test.case
> > > │   │   ├── dev.txt.shuffle.test.ner
> > > │   │   ├── dev.txt.shuffle.test.pos
> > > │   │   ├── dev.txt.shuffle.test.source.txt
> > > │   │   └── dev.txt.shuffle.test.target.txt
> > > │   └── train
> > > │       ├── train.txt.bio
> > > │       ├── train.txt.case
> > > │       ├── train.txt.ner
> > > │       ├── train.txt.pos
> > > │       ├── train.txt.source.txt
> > > │       └── train.txt.target.txt
> > > ├── raw
> > > │   ├── dev.txt.shuffle.dev
> > > │   ├── dev.txt.shuffle.test
> > > │   └── train.txt
> > > └── Readme.txt
> > 
> > 
> > Thanks!!
> 
> Sorry，this paper is so long ago. Try this url https://onedrive.live.com/?authkey=%21AJOw8oWPiHLhHNQ&id=3DDD4E15ECA69238%21200&cid=3DDD4E15ECA69238

@sion-zcfei Does this link exist? I am unable to access it.

**Comment by 2023aa05142** [comment]
@sion-zcfei Access denied what I am getting
